<?xml version="1.0"?>
<package format="3">
  <name>go1_control</name>
  <version>0.0.1</version>
  <description>Go1 motor control</description>
  <maintainer email="chase@email.com">chase</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>ros2_unitree_legged_msgs</depend>
  <buildtool_depend>ament_python</buildtool_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
